### ISSUE TITLE
"Your irrelevant project" in CONTRIBUTING.md sounds hostile

### ISSUE THREAD

**Issue by SammyForReal** [tomodachi94/awesome-computercraft#22]
I noticed one minor points about the `contribution.md` file that I feel like should be adjusted:

`2. Be relevant to ComputerCraft. It could be an awesome ComputerCraft extension mod, or an awesome tutorial. It cannot be your friend's cat's Facebook page, or your irrelevant project.`
I mainly dont like the last part here: _"...or your irrelevant project"_. First of: **It sounds very rude.** It also is not precise enough. _What if my project **IS** ComputerCraft related? When is a project irrelevant? etc._   
I feel like we should rephrase it. Maybe something like _"... or your java script auto-corrector"_? _(Just as an example.)_ This one would be more funny and still makes it clear that this repository is not for - in this scope - irrelevant stuff, while keeping a nice tone.

**Comment by tomodachi94** [comment]
That sounds like a really good change. I believe I made a typo/brain fart; I meant to have it read "**unrelated** project", but your idea sounds funnier and lighter-hearted. I'll integrate this later today or tomorrow, but you're also welcome to open a PR if you want it sooner. :)

**Comment by tomodachi94** [comment]
I've made a branch for improvements to the CONTRIBUTING.md file. I'm also planning on making a few other changes for the documentation; most notably, I'm moving the FAQ from the GitHub Wiki onto the main repository for greater visibility.
