### ISSUE TITLE
`CONTRIBUTING.md`/`FAQ.md` on project-awesome.org are 404s

### ISSUE THREAD

**Issue by fatboychummy** [tomodachi94/awesome-computercraft#27]
![image](https://github.com/tomodachi94/awesome-computercraft/assets/39929480/421b0ec7-ea81-4baa-8d68-ed378509169e)

They link to [https://project-awesome.org/tomodachi94/CONTRIBUTING.md](https://project-awesome.org/tomodachi94/CONTRIBUTING.md) and [https://project-awesome.org/tomodachi94/FAQ.md](https://project-awesome.org/tomodachi94/FAQ.md), which are 404's.

**Comment by tomodachi94** [comment]
Thank you for your report.

This is an issue with project-awesome.org's implementation; they do not handle relative links correctly. Closing, please file a report upstream.

**Comment by tomodachi94** [comment]
Other issues with project-awesome.org: https://github.com/Dvergar/awesome-haxe-gamedev/issues/11
