### ISSUE TITLE
Description for `cc-mek-scada` is slightly wrong

### ISSUE THREAD

**Issue by samuelh2005** [tomodachi94/awesome-computercraft#39]
`cc-mek-scada` describes it self as

> Configurable ComputerCraft SCADA system for multi-reactor control of Mekanism fission reactors with a GUI, automatic safety features, waste processing control, and more!

however, this repository describes it as

>  Integral management of a Mekanism factory.

The reason why I think this is wrong since `cc-mek-scada`  is management for fission reactors and not any generic factory. The description could be changed to "Integral management of Mekanism fission reactors`.

**Comment by tomodachi94** [comment]
Good catch. Fixed.
