### ISSUE TITLE
Add the Legendary lp Shop Software by PG231

### ISSUE THREAD

**Issue by creeloper27** [tomodachi94/awesome-computercraft#57]
### What is the name of the thing you want added?

lp
(PG231 just Open Sourced his legendary lp Shop Software in the switchcraft3 support discord channel)

### Summarize what the thing is or does.

Shop with intelligent pricing algorithms for ComputerCraft

### Where is the thing located on the Internet?

https://github.com/migeyel/lp
https://discord.com/channels/198130613759246337/1277642525401940064/1289326856671072337

### What category does the project fit best in?

Lua programs

### Are you the author of this thing?

No, I am not the author of this thing.

### Do you think the thing is awesome?

- [X] Yes, this is awesome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tomodachi94** [comment]
Added, thank you! ❤️
