### ISSUE TITLE
Add colorful and colorful2 (the rewrite still not finished) by znepb

### ISSUE THREAD

**Issue by creeloper27** [tomodachi94/awesome-computercraft#58]
### What is the name of the thing you want added?

colorful and colorful2
(znepb just Open Sourced his colorful and colorful2 (rewrite still not finished) Shop Software in the switchcraft3 support discord channel)

### Summarize what the thing is or does.

> a custom-built store which sold colorful blocks on SwitchCraft 3. It also featured an ink cartridge filler, shulker box filler, remote monitoring, and other features. I hope I didn't miss any components

### Where is the thing located on the Internet?

https://github.com/znepb/colorful
https://github.com/znepb/colorful2
https://discord.com/channels/198130613759246337/1277642525401940064/1289472668290121749

### What category does the project fit best in?

Lua programs

### Are you the author of this thing?

No, I am not the author of this thing.

### Do you think the thing is awesome?

- [X] Yes, this is awesome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tomodachi94** [comment]
I added colorful to the list. I'm choosing not to add colorful2 because it's incomplete. Per [the guidelines](https://github.com/tomodachi94/awesome-computercraft/blob/main/CONTRIBUTING.md#inclusion-criteria):

> If you want an item to be added to the list, it must:
> [...]
> 3. Can be immediately used. It has to have an installation script, or (in the case of literature) be immediately readable.
