### ISSUE TITLE
Add znepb's printshop

### ISSUE THREAD

**Issue by creeloper27** [tomodachi94/awesome-computercraft#60]
### What is the name of the thing you want added?

znepb's printshop
(znepb just Open Sourced his printshop in the switchcraft3 support discord channel)

### Summarize what the thing is or does.

> code that ran his print shop on SwitchCraft 3

### Where is the thing located on the Internet?

https://github.com/znepb/printshop
https://discord.com/channels/198130613759246337/1277642525401940064/1289472668290121749

### What category does the project fit best in?

Lua programs

### Are you the author of this thing?

No, I am not the author of this thing.

### Do you think the thing is awesome?

- [X] Yes, this is awesome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by znepb** [comment]
I second this

**Comment by tomodachi94** [comment]
I'm having trouble describing this. What does it do? What is a "print shop"? I'm envisioning something that allows users to pay for printing things, but I'm not sure this is an accurate description. What is printed? Can players print their own designs, or is there a list of designs that must be chosen from?

**Comment by tomodachi94** [comment]
Cc @creeloper27 @znepb

**Comment by znepb** [comment]
It printed out 3D prints and posters on SC3. They'd pay for prints and could provide their own designs via a URL that would be downloaded.
